blank_issues_enabled: false
contact_links:
  - name: Bugcord Support Server
    url: https://discord.gg/EsNDvBaHVU
    about: If you need help regarding Bugcord or plugins for Bugcord, please join our support server.
